package com.ueh.my.domain;

import static com.ueh.my.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class EventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventAllPropertiesEquals(Event expected, Event actual) {
        assertEventAutoGeneratedPropertiesEquals(expected, actual);
        assertEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventAllUpdatablePropertiesEquals(Event expected, Event actual) {
        assertEventUpdatableFieldsEquals(expected, actual);
        assertEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventAutoGeneratedPropertiesEquals(Event expected, Event actual) {
        assertThat(actual)
            .as("Verify Event auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventUpdatableFieldsEquals(Event expected, Event actual) {
        assertThat(actual)
            .as("Verify Event relevant properties")
            .satisfies(a -> assertThat(a.getEventName()).as("check eventName").isEqualTo(expected.getEventName()))
            .satisfies(a -> assertThat(a.getEventDesc()).as("check eventDesc").isEqualTo(expected.getEventDesc()))
            .satisfies(a -> assertThat(a.getEventOrg()).as("check eventOrg").isEqualTo(expected.getEventOrg()))
            .satisfies(a ->
                assertThat(a.getEventDate())
                    .as("check eventDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getEventDate())
            )
            .satisfies(a -> assertThat(a.getEventLocation()).as("check eventLocation").isEqualTo(expected.getEventLocation()))
            .satisfies(a -> assertThat(a.getEventPoster()).as("check eventPoster").isEqualTo(expected.getEventPoster()))
            .satisfies(a ->
                assertThat(a.getEventPosterContentType())
                    .as("check eventPoster contenty type")
                    .isEqualTo(expected.getEventPosterContentType())
            )
            .satisfies(a -> assertThat(a.getEnteredBy()).as("check enteredBy").isEqualTo(expected.getEnteredBy()))
            .satisfies(a ->
                assertThat(a.getEnteredDate())
                    .as("check enteredDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getEnteredDate())
            )
            .satisfies(a -> assertThat(a.getModifiedBy()).as("check modifiedBy").isEqualTo(expected.getModifiedBy()))
            .satisfies(a ->
                assertThat(a.getModifiedDate())
                    .as("check modifiedDate")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getModifiedDate())
            )
            .satisfies(a -> assertThat(a.getEventStatus()).as("check eventStatus").isEqualTo(expected.getEventStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventUpdatableRelationshipsEquals(Event expected, Event actual) {
        // empty method
    }
}
